# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## 1. Installation Instructions
    
    conda install numpy
    

In [1]:
!conda install matplotlib numpy

Solving environment: ...working... done

# All requested packages already installed.



### Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We will focus on some of the most important aspects of Numpy: vectors, arrays, matrices, and number generation.

## 2. Numpy Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
* The number of dimensions is the rank of the array
* The shape of an array is a tuple of integers giving the size of the array along each dimension. 

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

### 2.1. Creating NumPy Arrays from Python List


We can create an array by directly converting a list or list of lists:

In [8]:
# Casting
my_list = [1,2,3]
my_list_ar = np.array(my_list)
my_list_ar

array([1, 2, 3])

In [9]:
my_list_ar.astype(float)

array([1., 2., 3.])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2.2. Generating arrays from bulid-in functions

There are lots of built-in ways to generate Arrays: 
- **arange** : Return evenly spaced values within a given interval.
- **linspace** : Return evenly spaced numbers over a specified interval (prefered to arange).
- **zeros** : Return a new array of given shape and type, filled with zeros.
- **zeros_like** : Return an array of zeros with the same shape and type as a given array.
- **ones** : Return a new array setting values to one.
- **fill** : Return a new array of given shape filled with value (array exists aleardy).
- **full** : Creates an array of the given shape initialized with the given value (new one). 
- **empty** : Return a new array of given shape and type, without initializing entries. its content is not predictable. `empty`, unlike `zeros`, does not set the array values to zero,
and may therefore be marginally faster.  On the other hand, it requires
the user to manually set all the values in the array, and should be
used with caution.
- **eyes** : Return a 2-D array with ones on the diagonal and zeros elsewhere.
- **identity** : (almost) equivalent function
- **diag** : diagonal 2-D array from a 1-D array specified by the user.

In [12]:
import numpy as np
help (np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

### 2.3. Performance measurement
The key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [13]:
c = range(10000)
%timeit [i**3 for i in c]

2.15 ms ± 26.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

15.3 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Still not convinced? want to see one more intresting example (more details will given in section `"Broadcasting and Vectorization"`).

We can do everything without even writing a loop? yes... 

### 2.4. Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

In [6]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
a.shape

(3, 4)

In [8]:
a.ndim  # equal to len(a.shape)

2

In [9]:
a.size

12

### 2.5. Array attributes and methods 

#### 2.5.1. `dtype`
NumPy's `ndarray`s are also efficient in part because all their elements must have the same type (usually numbers).
You can check what the data type is by looking at the `dtype` attribute:

In [12]:
### dtype: You can also grab the data type of the object in the array
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

print(arr.dtype, arr)

int32 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [13]:
arr = np.arange(0, 25.0)
print(arr.dtype, arr)

float64 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


Instead of letting NumPy guess what data type to use, you can set it explicitly when creating an array by setting the `dtype` parameter:

In [17]:
d = np.arange(1, 5, dtype=np.float64)
print(d.dtype, d)

float64 [1. 2. 3. 4.]


Available data types include `int8`, `int16`, `int32`, `int64`, `uint8`|`16`|`32`|`64`, `float16`|`32`|`64` and `complex64`|`128`. Check out [the documentation](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html) for the full list.


In [19]:
l = np.array([1,2,3,4],dtype=np.string_)

In [20]:
l

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [21]:
l.astype(int)

array([1, 2, 3, 4])

In [22]:
l = np.array([1,2,3,4],dtype='S2')
l

array([b'1', b'2', b'3', b'4'], dtype='|S2')

#### 2.5.2. `Reshape`
Changing the shape of an `ndarray` is as simple as setting its `shape` attribute. However, the array's size must remain the same (in place).

In [30]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[26 49  9  4 32 34  2 18 47 14]


In [31]:
c = arr.reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
c[0] = 10 #changing some values

In [45]:
c

array([[10, 10, 10, 10, 10],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr #is also modified (a view)

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### 2.5.5. `ravel`
Finally, the `ravel` function returns a new one-dimensional `ndarray` that also points to the same data:

In [49]:
d = c.ravel()

In [50]:
d.shape

(25,)

In [56]:
d.ndim

1

In [57]:
d

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

`c and d` have different memory addresses but the are viewing the same data in memory: !!!!

In [54]:
c[0] = 99
c

array([[99, 99, 99, 99, 99],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
d

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### 2.5.6. `max, min, argmax, argmin`

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [23]:
ranarr

array([32, 15, 10, 31, 36, 38, 11, 16, 45, 15])

In [24]:
ranarr.max()

45

In [25]:
ranarr.argmax()

8

In [26]:
ranarr.min()

10

In [27]:
ranarr.argmin()

2

In [32]:
print(c)
c.max(axis=1)

[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  9, 14, 19, 24])

#### 2.5.7. Upcasting
When trying to combine arrays with different `dtype`s, NumPy will *upcast* to a type capable of handling all possible values (regardless of what the *actual* values are).

In [58]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [59]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

int16 [ 5  7  9 11 13]


Note that `int16` is required to represent all *possible* `int8` and `uint8` values (from -128 to 255), even though in this case a uint8 would have sufficed.

In [60]:
k3 = k1 + 1.5
print(k3.dtype, k3)

float64 [1.5 2.5 3.5 4.5 5.5]
